<?php //<?php Buscar prêmios do banco de dados try {<?php $stmt =<?php $pdo->query("<?php SELECT rp.nome,<?php rp.icone,<?php rp.valor <?php FROM raspadinha_premios rp <?php JOIN raspadinhas r ON rp.raspadinha_id =<?php r.id <?php WHERE rp.valor ><?php 0 <?php ORDER BY RAND()<?php LIMIT 20 <?php ");<?php $premios =<?php $stmt->fetchAll(PDO::FETCH_ASSOC);<?php 
}<?php catch (PDOException $e)<?php {<?php $premios =<?php [];<?php 
}<?php //<?php Lista de nomes brasileiros aleatórios $nomes =<?php [<?php 'Ana',<?php 'João',<?php 'Maria',<?php 'Pedro',<?php 'Carla',<?php 'Lucas',<?php 'Fernanda',<?php 'Rafael',<?php 'Juliana',<?php 'Bruno',<?php 'Camila',<?php 'Diego',<?php 'Beatriz',<?php 'Thiago',<?php 'Larissa',<?php 'André',<?php 'Patrícia',<?php 'Gustavo',<?php 'Isabela',<?php 'Felipe',<?php 'Amanda',<?php 'Rodrigo',<?php 'Natália',<?php 'Gabriel',<?php 'Letícia',<?php 'Mateus',<?php 'Carolina',<?php 'Leonardo',<?php 'Vanessa',<?php 'Marcelo',<?php 'Priscila',<?php 'Daniel',<?php 'Roberta',<?php 'Vinícius',<?php 'Mônica',<?php 'Ricardo',<?php 'Adriana',<?php 'Fábio',<?php 'Cristina',<?php 'Alexandre',<?php 'Silvia',<?php 'Eduardo',<?php 'Renata',<?php 'Carlos',<?php 'Tatiane',<?php 'Paulo',<?php 'Débora',<?php 'Antônio',<?php 'Sandra',<?php 'José',<?php 'Márcia',<?php 'Roberto',<?php 'Luciana',<?php 'Marcos',<?php 'Eliane',<?php 'Francisco',<?php 'Regina',<?php 'Fernando',<?php 'Marta',<?php 'Luiz',<?php 'Denise',<?php 'Sérgio',<?php 'Cláudia',<?php 'Jorge',<?php 'Vera',<?php 'Raimundo',<?php 'Solange',<?php 'Manoel',<?php 'Rosana',<?php 'Edson',<?php 'Lúcia',<?php 'Wilson',<?php 'Simone',<?php 'Sebastião',<?php 'Teresa',<?php 'Antônio',<?php 'Aparecida',<?php 'Valdir',<?php 'Fátima',<?php 'João',<?php 'Cleusa',<?php 'Benedito',<?php 'Rita',<?php 'Nelson',<?php 'Marlene',<?php 'Davi',<?php 'Célia',<?php 'Geraldo',<?php 'Neusa',<?php 'Ademir',<?php 'Ivone',<?php 'Miguel',<?php 'Irene',<?php 'Waldir',<?php 'Sônia',<?php 'Benedita',<?php 'Valter',<?php 'Lourdes',<?php 'Reinaldo',<?php 'Terezinha',<?php 'Alcides'<?php 
];<?php //<?php Gerar ganhadores com dados aleatórios $ganhadores =<?php [];<?php 
$valor_total_distribuido =<?php 0;<?php foreach ($premios as $premio)<?php {<?php $nome_aleatorio =<?php $nomes[array_rand($nomes)];<?php $tempo_aleatorio =<?php rand(1,<?php 60);<?php //<?php Entre 1 e 60 minutos <?php $ganhadores[]<?php =<?php [<?php 'nome'<?php =><?php $nome_aleatorio,<?php 'premio'<?php =><?php $premio['nome'],<?php 'icone'<?php =><?php $premio['icone'],<?php 'valor'<?php =><?php $premio['valor'],<?php 'tempo'<?php =><?php $tempo_aleatorio <?php ];<?php <?php $valor_total_distribuido +=<?php $premio['valor'];<?php 
}<?php //<?php Duplicar para efeito infinito $ganhadores_duplicados =<?php array_merge($ganhadores,<?php $ganhadores);<?php 
?><?php <section class="winners-section"><?php <div class="winners-container"><?php <div class="winners-header"><?php <h2 class="winners-title">Últimos Ganhadores</h2><?php <div class="total-distributed"><?php <span class="distributed-label">Prêmios Distribuídos</span><?php <span class="distributed-value">R$<?php <?php=<?php number_format($valor_total_distribuido,<?php 2,<?php ',',<?php '.')<?php ?></span><?php </div><?php </div><?php <?php <div class="winners-carousel"><?php <div class="winners-track"><?php <?php foreach ($ganhadores_duplicados as $ganhador):<?php ?><?php <div class="winner-item"><?php <div class="winner-avatar"><?php <?php if (!empty($ganhador['icone'])<?php &&<?php file_exists($_SERVER['DOCUMENT_ROOT']<?php .<?php $ganhador['icone'])):<?php ?><?php <img src="<?php=<?php htmlspecialchars($ganhador['icone'])<?php ?>"<?php alt="<?php=<?php htmlspecialchars($ganhador['premio'])<?php ?>"<?php class="winner-image"><?php <?php else:<?php ?><?php <div class="winner-placeholder"><?php <i class="bi bi-gift"></i><?php </div><?php <?php endif;<?php ?><?php </div><?php <?php <div class="winner-info"><?php <div class="winner-name">***<?php=<?php strtolower(substr($ganhador['nome'],<?php 0,<?php 1))<?php .<?php str_repeat('*',<?php strlen($ganhador['nome'])<?php -<?php 1)<?php ?></div><?php <div class="winner-time">há<?php <?php=<?php $ganhador['tempo']<?php ?><?php min</div><?php </div><?php <?php <div class="winner-prize"><?php <div class="prize-value">R$<?php <?php=<?php number_format($ganhador['valor'],<?php 0,<?php ',',<?php '.')<?php ?></div><?php <div class="prize-type"><?php <?php if ($ganhador['valor']<?php >=<?php 1000):<?php ?><?php <span class="prize-badge premium">PRÊMIO</span><?php <?php else:<?php ?><?php <span class="prize-badge standard">PIX</span><?php <?php endif;<?php ?><?php </div><?php </div><?php </div><?php <?php endforeach;<?php ?><?php </div><?php </div><?php </div><?php 
</section><?php <style><?php 
/*<?php Winners Section */<?php 
.winners-section {<?php padding:<?php 3rem 2rem;<?php overflow:<?php hidden;<?php 
}<?php .winners-container {<?php max-width:<?php 1400px;<?php margin:<?php 0 auto;<?php 
}<?php .winners-header {<?php display:<?php flex;<?php justify-content:<?php space-between;<?php align-items:<?php center;<?php margin-bottom:<?php 2rem;<?php flex-wrap:<?php wrap;<?php gap:<?php 1rem;<?php 
}<?php .winners-title {<?php font-size:<?php 2rem;<?php font-weight:<?php 800;<?php color:<?php #ffffff;<?php margin:<?php 0;<?php 
}<?php .total-distributed {<?php text-align:<?php right;<?php 
}<?php .distributed-label {<?php display:<?php block;<?php font-size:<?php 0.9rem;<?php color:<?php #9ca3af;<?php margin-bottom:<?php 0.25rem;<?php 
}<?php .distributed-value {<?php font-size:<?php 1.5rem;<?php font-weight:<?php 800;<?php color:<?php #22c55e;<?php display:<?php block;<?php 
}<?php .winners-carousel {<?php position:<?php relative;<?php overflow:<?php hidden;<?php mask:<?php linear-gradient(90deg,<?php transparent,<?php black 5%,<?php black 95%,<?php transparent);<?php -webkit-mask:<?php linear-gradient(90deg,<?php transparent,<?php black 5%,<?php black 95%,<?php transparent);<?php 
}<?php .winners-track {<?php display:<?php flex;<?php gap:<?php 1rem;<?php animation:<?php scroll-winners 60s linear infinite;<?php width:<?php fit-content;<?php 
}<?php @keyframes scroll-winners {<?php 0%<?php {<?php transform:<?php translateX(0);<?php }<?php 100%<?php {<?php transform:<?php translateX(-50%);<?php }<?php 
}<?php .winner-item {<?php flex-shrink:<?php 0;<?php width:<?php 280px;<?php background:<?php linear-gradient(145deg,<?php rgba(20,<?php 20,<?php 20,<?php 0.8)<?php 0%,<?php rgba(10,<?php 10,<?php 10,<?php 0.9)<?php 100%);<?php border:<?php 1px solid rgba(34,<?php 197,<?php 94,<?php 0.2);<?php border-radius:<?php 16px;<?php padding:<?php 1.5rem;<?php display:<?php flex;<?php align-items:<?php center;<?php gap:<?php 1rem;<?php backdrop-filter:<?php blur(20px);<?php transition:<?php all 0.3s ease;<?php 
}<?php .winner-item:hover {<?php border-color:<?php rgba(34,<?php 197,<?php 94,<?php 0.4);<?php transform:<?php translateY(-2px);<?php box-shadow:<?php 0 8px 25px rgba(0,<?php 0,<?php 0,<?php 0.2);<?php 
}<?php .winner-avatar {<?php width:<?php 50px;<?php height:<?php 50px;<?php border-radius:<?php 50%;<?php overflow:<?php hidden;<?php flex-shrink:<?php 0;<?php background:<?php linear-gradient(135deg,<?php rgba(34,<?php 197,<?php 94,<?php 0.2),<?php rgba(16,<?php 185,<?php 129,<?php 0.1));<?php border:<?php 2px solid rgba(34,<?php 197,<?php 94,<?php 0.3);<?php display:<?php flex;<?php align-items:<?php center;<?php justify-content:<?php center;<?php 
}<?php .winner-image {<?php width:<?php 100%;<?php height:<?php 100%;<?php object-fit:<?php cover;<?php 
}<?php .winner-placeholder {<?php color:<?php #22c55e;<?php font-size:<?php 1.5rem;<?php 
}<?php .winner-info {<?php flex:<?php 1;<?php min-width:<?php 0;<?php 
}<?php .winner-name {<?php font-size:<?php 1rem;<?php font-weight:<?php 600;<?php color:<?php #ffffff;<?php margin-bottom:<?php 0.25rem;<?php text-overflow:<?php ellipsis;<?php overflow:<?php hidden;<?php white-space:<?php nowrap;<?php 
}<?php .winner-time {<?php font-size:<?php 0.8rem;<?php color:<?php #9ca3af;<?php 
}<?php .winner-prize {<?php text-align:<?php right;<?php flex-shrink:<?php 0;<?php 
}<?php .prize-value {<?php font-size:<?php 1.1rem;<?php font-weight:<?php 700;<?php color:<?php #22c55e;<?php margin-bottom:<?php 0.25rem;<?php 
}<?php .prize-type {<?php display:<?php flex;<?php justify-content:<?php flex-end;<?php 
}<?php .prize-badge {<?php font-size:<?php 0.7rem;<?php font-weight:<?php 600;<?php padding:<?php 0.2rem 0.5rem;<?php border-radius:<?php 12px;<?php text-transform:<?php uppercase;<?php letter-spacing:<?php 0.5px;<?php 
}<?php .prize-badge.premium {<?php background:<?php linear-gradient(135deg,<?php #f59e0b,<?php #d97706);<?php color:<?php white;<?php 
}<?php .prize-badge.standard {<?php background:<?php linear-gradient(135deg,<?php #22c55e,<?php #16a34a);<?php color:<?php white;<?php 
}<?php /*<?php Pause animation on hover */<?php 
.winners-carousel:hover .winners-track {<?php animation-play-state:<?php paused;<?php 
}<?php /*<?php Mobile Responsive */<?php 
@media (max-width:<?php 768px)<?php {<?php .winners-section {<?php padding:<?php 2rem 1rem;<?php }<?php <?php .winners-header {<?php flex-direction:<?php column;<?php align-items:<?php flex-start;<?php text-align:<?php left;<?php }<?php <?php .winners-title {<?php font-size:<?php 1.6rem;<?php }<?php <?php .total-distributed {<?php text-align:<?php left;<?php }<?php <?php .distributed-value {<?php font-size:<?php 1.3rem;<?php }<?php <?php .winner-item {<?php width:<?php 250px;<?php padding:<?php 1rem;<?php }<?php <?php .winner-avatar {<?php width:<?php 40px;<?php height:<?php 40px;<?php }<?php <?php .winner-placeholder {<?php font-size:<?php 1.2rem;<?php }<?php <?php .winner-name {<?php font-size:<?php 0.9rem;<?php }<?php <?php .winner-time {<?php font-size:<?php 0.75rem;<?php }<?php <?php .prize-value {<?php font-size:<?php 1rem;<?php }<?php <?php .winners-track {<?php animation-duration:<?php 45s;<?php }<?php 
}<?php @media (max-width:<?php 480px)<?php {<?php .winner-item {<?php width:<?php 220px;<?php padding:<?php 0.875rem;<?php gap:<?php 0.75rem;<?php }<?php <?php .winner-avatar {<?php width:<?php 35px;<?php height:<?php 35px;<?php }<?php <?php .winner-name {<?php font-size:<?php 0.85rem;<?php }<?php <?php .prize-value {<?php font-size:<?php 0.9rem;<?php }<?php <?php .prize-badge {<?php font-size:<?php 0.65rem;<?php padding:<?php 0.15rem 0.4rem;<?php }<?php 
}<?php /*<?php Loading state for images */<?php 
.winner-image {<?php opacity:<?php 0;<?php transition:<?php opacity 0.3s ease;<?php 
}<?php .winner-image.loaded {<?php opacity:<?php 1;<?php 
}<?php 
</style><?php <script><?php 
document.addEventListener('DOMContentLoaded',<?php function()<?php {<?php //<?php Lazy load images <?php const images =<?php document.querySelectorAll('.winner-image');<?php images.forEach(img =><?php {<?php img.onload =<?php function()<?php {<?php this.classList.add('loaded');<?php };<?php <?php //<?php If image is already loaded <?php if (img.complete)<?php {<?php img.classList.add('loaded');<?php }<?php });<?php <?php console.log('%c🏆<?php Últimos Ganhadores carregados!',<?php 'color:<?php #22c55e;<?php font-size:<?php 14px;<?php font-weight:<?php bold;');<?php 
});<?php 
</script>