<footer class="footer"><?php <div class="footer-container"><?php <div class="footer-content"><?php <div><?php <div class="footer-brand"><?php <?php if ($logoSite &&<?php file_exists($_SERVER['DOCUMENT_ROOT']<?php .<?php $logoSite)):<?php ?><?php <img src="<?php=<?php htmlspecialchars($logoSite)<?php ?>"<?php alt="<?php=<?php htmlspecialchars($nomeSite)<?php ?>"<?php class="footer-logo-image"><?php <?php else:<?php ?><?php <div class="footer-logo-icon"><?php <?php=<?php strtoupper(substr($nomeSite,<?php 0,<?php 1))<?php ?><?php </div><?php <?php endif;<?php ?><?php </div><?php <p class="footer-description"><?php ©<?php 2025 <?php echo $nomeSite;<?php ?>.<?php Todos os direitos reservados.<?php </p><?php <p class="footer-description"><?php Raspadinhas e outros jogos de azar são regulamentados e cobertos pela nossa licença de jogos.<?php Jogue com responsabilidade.<?php </p><?php </div><?php <?php <div class="footer-section"><?php <h3>Regulamentos</h3><?php <ul class="footer-links"><?php <li><a href="#">Jogo responsável</a></li><?php <li><a href="#">Política de Privacidade</a></li><?php <li><a href="#">Termos de Uso</a></li><?php </ul><?php </div><?php <?php <div class="footer-section"><?php <h3>Ajuda</h3><?php <ul class="footer-links"><?php <li><a href="#">Perguntas Frequentes</a></li><?php <li><a href="#">Como Jogar</a></li><?php <li><a href="#">Suporte Técnico</a></li><?php </ul><?php </div><?php </div><?php </div><?php 
</footer><?php <style><?php 
/*<?php Footer Logo Styles */<?php 
.footer-brand {<?php display:<?php flex;<?php align-items:<?php center;<?php gap:<?php 0.75rem;<?php margin-bottom:<?php 1rem;<?php 
}<?php .footer-logo-image {<?php height:<?php 40px;<?php width:<?php auto;<?php max-width:<?php 150px;<?php object-fit:<?php contain;<?php transition:<?php all 0.3s ease;<?php 
}<?php .footer-logo-image:hover {<?php transform:<?php scale(1.02);<?php 
}<?php .footer-logo-icon {<?php width:<?php 40px;<?php height:<?php 40px;<?php background:<?php linear-gradient(135deg,<?php #22c55e 0%,<?php #16a34a 100%);<?php border-radius:<?php 10px;<?php display:<?php flex;<?php align-items:<?php center;<?php justify-content:<?php center;<?php font-size:<?php 1.2rem;<?php color:<?php #ffffff;<?php font-weight:<?php 800;<?php box-shadow:<?php 0 4px 12px rgba(34,<?php 197,<?php 94,<?php 0.3);<?php transition:<?php all 0.3s ease;<?php 
}<?php .footer-logo-icon:hover {<?php box-shadow:<?php 0 6px 16px rgba(34,<?php 197,<?php 94,<?php 0.4);<?php transform:<?php translateY(-1px);<?php 
}<?php .footer-brand span {<?php font-size:<?php 1.25rem;<?php font-weight:<?php 700;<?php color:<?php white;<?php 
}<?php /*<?php Footer Base Styles */<?php 
.footer {<?php background:<?php linear-gradient(145deg,<?php #0a0a0a 0%,<?php #1a1a1a 100%);<?php border-top:<?php 1px solid rgba(255,<?php 255,<?php 255,<?php 0.05);<?php margin-top:<?php 4rem;<?php 
}<?php .footer-container {<?php max-width:<?php 1400px;<?php margin:<?php 0 auto;<?php padding:<?php 3rem 2rem 2rem;<?php 
}<?php .footer-content {<?php display:<?php grid;<?php grid-template-columns:<?php 2fr 1fr 1fr;<?php gap:<?php 3rem;<?php margin-bottom:<?php 2rem;<?php 
}<?php .footer-section h3 {<?php color:<?php white;<?php font-size:<?php 1.1rem;<?php font-weight:<?php 600;<?php margin-bottom:<?php 1rem;<?php border-bottom:<?php 2px solid #22c55e;<?php padding-bottom:<?php 0.5rem;<?php display:<?php inline-block;<?php 
}<?php .footer-links {<?php list-style:<?php none;<?php padding:<?php 0;<?php 
}<?php .footer-links li {<?php margin-bottom:<?php 0.75rem;<?php 
}<?php .footer-links a {<?php color:<?php #9ca3af;<?php text-decoration:<?php none;<?php transition:<?php all 0.3s ease;<?php font-size:<?php 0.95rem;<?php 
}<?php .footer-links a:hover {<?php color:<?php #22c55e;<?php padding-left:<?php 0.5rem;<?php 
}<?php .footer-description {<?php color:<?php #6b7280;<?php font-size:<?php 0.9rem;<?php line-height:<?php 1.5;<?php margin-bottom:<?php 1rem;<?php 
}<?php /*<?php Responsive */<?php 
@media (max-width:<?php 768px)<?php {<?php .footer-content {<?php grid-template-columns:<?php 1fr;<?php gap:<?php 2rem;<?php }<?php <?php .footer-container {<?php padding:<?php 2rem 1rem 1.5rem;<?php }<?php <?php .footer-brand {<?php gap:<?php 0.5rem;<?php }<?php <?php .footer-logo-image {<?php height:<?php 35px;<?php }<?php <?php .footer-logo-icon {<?php width:<?php 35px;<?php height:<?php 35px;<?php font-size:<?php 1.1rem;<?php border-radius:<?php 8px;<?php }<?php <?php .footer-brand span {<?php font-size:<?php 1.1rem;<?php }<?php 
}<?php @media (max-width:<?php 480px)<?php {<?php .footer-brand {<?php gap:<?php 0.4rem;<?php }<?php <?php .footer-logo-image {<?php height:<?php 32px;<?php }<?php <?php .footer-logo-icon {<?php width:<?php 32px;<?php height:<?php 32px;<?php font-size:<?php 1rem;<?php border-radius:<?php 6px;<?php }<?php <?php .footer-brand span {<?php font-size:<?php 1rem;<?php }<?php <?php .footer-section h3 {<?php font-size:<?php 1rem;<?php }<?php <?php .footer-links a {<?php font-size:<?php 0.9rem;<?php }<?php <?php .footer-description {<?php font-size:<?php 0.85rem;<?php }<?php 
}<?php 
</style>