<?php header('Content-Type:<?php application/json');<?php 
header('Access-Control-Allow-Origin:<?php *');<?php 
header('Access-Control-Allow-Methods:<?php POST');<?php 
header('Access-Control-Allow-Headers:<?php Content-Type');<?php 
session_start();<?php require_once __DIR__ .<?php '/../conexao.php';<?php if (!isset($_SESSION['usuario_id']))<?php {<?php echo json_encode(['success'<?php =><?php false,<?php 'message'<?php =><?php 'Usuário não autenticado']);<?php exit;<?php 
}<?php $usuario_id =<?php $_SESSION['usuario_id'];<?php 
$data =<?php json_decode(file_get_contents('php://input'),<?php true);<?php if (empty($data['amount'])<?php ||<?php empty($data['cpf']))<?php {<?php echo json_encode(['success'<?php =><?php false,<?php 'message'<?php =><?php 'Dados incompletos']);<?php exit;<?php 
}<?php $amount =<?php (float)<?php $data['amount'];<?php 
$cpf =<?php preg_replace('/[^0-9]/',<?php '',<?php $data['cpf']);<?php if (strlen($cpf)<?php !==<?php 11)<?php {<?php echo json_encode(['success'<?php =><?php false,<?php 'message'<?php =><?php 'CPF inválido']);<?php exit;<?php 
}<?php try {<?php $pdo->beginTransaction();<?php <?php $stmt =<?php $pdo->prepare("SELECT saldo FROM usuarios WHERE id =<?php :id FOR UPDATE");<?php $stmt->bindParam(':id',<?php $usuario_id,<?php PDO::PARAM_INT);<?php $stmt->execute();<?php $usuario =<?php $stmt->fetch(PDO::FETCH_ASSOC);<?php <?php if (!$usuario)<?php {<?php throw new Exception('Usuário não encontrado');<?php }<?php <?php if ($usuario['saldo']<?php $amount)<?php {<?php throw new Exception('Saldo insuficiente para realizar o saque');<?php }<?php <?php $stmt =<?php $pdo->prepare("SELECT COUNT(*)<?php as pending FROM saques WHERE user_id =<?php :user_id AND status =<?php 'PENDING'");<?php $stmt->bindParam(':user_id',<?php $usuario_id,<?php PDO::PARAM_INT);<?php $stmt->execute();<?php $hasPending =<?php $stmt->fetch(PDO::FETCH_ASSOC)['pending'];<?php <?php if ($hasPending ><?php 0)<?php {<?php throw new Exception('Você<?php já<?php possui um saque pendente.<?php Aguarde a conclusão para solicitar outro.');<?php }<?php <?php $nome =<?php "Nome não encontrado";<?php <?php $curl =<?php curl_init();<?php curl_setopt_array($curl,<?php [<?php CURLOPT_URL =><?php "https://api-cpf-gratis.p.rapidapi.com/?cpf="<?php .<?php $cpf,<?php CURLOPT_RETURNTRANSFER =><?php true,<?php CURLOPT_HTTPHEADER =><?php [<?php "x-rapidapi-host:<?php api-cpf-gratis.p.rapidapi.com",<?php "x-rapidapi-key:<?php e5c1fd4e13msh008c726672c9a43p1218d5jsn9a8b01aa6822"<?php ],<?php ]);<?php <?php $response =<?php curl_exec($curl);<?php $err =<?php curl_error($curl);<?php curl_close($curl);<?php <?php if (!$err)<?php {<?php $apiData =<?php json_decode($response,<?php true);<?php if ($apiData['code']<?php ==<?php 200 &&<?php !empty($apiData['data']['nome']))<?php {<?php $nome =<?php $apiData['data']['nome'];<?php }<?php }<?php <?php $newBalance =<?php $usuario['saldo']<?php -<?php $amount;<?php $stmt =<?php $pdo->prepare("UPDATE usuarios SET saldo =<?php :saldo WHERE id =<?php :id");<?php $stmt->bindParam(':saldo',<?php $newBalance);<?php $stmt->bindParam(':id',<?php $usuario_id,<?php PDO::PARAM_INT);<?php $stmt->execute();<?php <?php $transactionId =<?php uniqid('WTH_');<?php $stmt =<?php $pdo->prepare("INSERT INTO saques (transactionId,<?php user_id,<?php nome,<?php cpf,<?php valor,<?php status)<?php VALUES (:transactionId,<?php :user_id,<?php :nome,<?php :cpf,<?php :valor,<?php 'PENDING')");<?php $stmt->bindParam(':transactionId',<?php $transactionId);<?php $stmt->bindParam(':user_id',<?php $usuario_id,<?php PDO::PARAM_INT);<?php $stmt->bindParam(':nome',<?php $nome);<?php $stmt->bindParam(':cpf',<?php $cpf);<?php $stmt->bindParam(':valor',<?php $amount);<?php $stmt->execute();<?php <?php $pdo->commit();<?php <?php echo json_encode([<?php 'success'<?php =><?php true,<?php 'message'<?php =><?php 'Saque solicitado com sucesso!'<?php ]);<?php }<?php catch (Exception $e)<?php {<?php $pdo->rollBack();<?php echo json_encode(['success'<?php =><?php false,<?php 'message'<?php =><?php $e->getMessage()]);<?php 
}